In [ ]:
# Earlier we have seen how to do using word2Vec.
# This notebook will show how to convert words of a sentence to vectors, using word embeddings.
# This will show training part of word embeddings

In [ ]:
# We are performing word embedding training because we have our own data.

In [ ]:
# Stepts for training
# Select set of Sentecnces
# Define Vocabulary size -> Number of unique words in a text corpus/para
# One hot encoding (OHE)
# Padding (Post Padding & Pre Padding on OHE)
# OHE values will get converted to vectors

## Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

## One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[443, 420, 141, 267], [443, 420, 141, 53], [443, 471, 141, 293], [423, 459, 23, 279, 122], [423, 459, 23, 279, 226], [475, 443, 128, 141, 87], [226, 196, 285, 279]]


If we Notice above, size of each sentence represented in list is not same. Therefore we perform Post & pre padding

## Word Embedding Represntation (post & pre padding)

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [ ]:
# Finding maximum sentence length
length=0
for sentence in sent:
  if len(sentence.split(' ')) > length:
    length = len(sentence.split(' '))

length


5

In [ ]:
## Post padding
sent_length= length + 3 # Adding 3 for extra zeros to show pre and post zeros
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[443 420 141 267   0   0   0   0]
 [443 420 141  53   0   0   0   0]
 [443 471 141 293   0   0   0   0]
 [423 459  23 279 122   0   0   0]
 [423 459  23 279 226   0   0   0]
 [475 443 128 141  87   0   0   0]
 [226 196 285 279   0   0   0   0]]


In [ ]:
## Pre padding
sent_length= length + 3 # Adding 3 for extra zeros to show pre and post zeros
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 443 420 141 267]
 [  0   0   0   0 443 420 141  53]
 [  0   0   0   0 443 471 141 293]
 [  0   0   0 423 459  23 279 122]
 [  0   0   0 423 459  23 279 226]
 [  0   0   0 475 443 128 141  87]
 [  0   0   0   0 226 196 285 279]]


In [ ]:
## Pre padding
sent_length= length
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0 443 420 141 267]
 [  0 443 420 141  53]
 [  0 443 471 141 293]
 [423 459  23 279 122]
 [423 459  23 279 226]
 [475 443 128 141  87]
 [  0 226 196 285 279]]


In [ ]:
## 10 Feature Representation dimention
dim=10

In [ ]:
voc_size

500

In [ ]:
# Creating sequestial model
model=Sequential()


model.add(Embedding(input_dim=voc_size,
                    output_dim= dim))
model.compile(optimizer='adam',
              loss='mse')

In [ ]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## **NOTE:-**
In this case, the output shape has ? for both the batch size and the sequence length because Keras will determine the sequence length dynamically based on the input data.



In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0, 443, 420, 141, 267], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step


array([[-0.01597375,  0.01124644,  0.04702612, -0.02477637, -0.02166818,
        -0.00692565,  0.00137762,  0.03707198,  0.04972422,  0.04412607],
       [-0.02947437, -0.00324265, -0.04161046, -0.00239938,  0.00184681,
         0.00483125,  0.02619633, -0.03283904,  0.0243705 , -0.03910375],
       [ 0.04267612, -0.03350116, -0.0234298 ,  0.00746056, -0.03464542,
         0.0317754 , -0.04463515,  0.03101057,  0.04890628,  0.01694882],
       [-0.03820832, -0.04938891,  0.03143836, -0.00529527, -0.02088292,
         0.01896072,  0.02210693,  0.02839288,  0.01945493, -0.02051385],
       [ 0.00772226, -0.04961765, -0.04692031,  0.00286301, -0.04634292,
        -0.03382219,  0.01582136, -0.01889046,  0.01990343,  0.03978669]],
      dtype=float32)

In [ ]:
for i in embedded_docs:
  print(model.predict(i))
#print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[-0.01597375  0.01124644  0.04702612 -0.02477637 -0.02166818 -0.00692565
   0.00137762  0.03707198  0.04972422  0.04412607]
 [-0.02947437 -0.00324265 -0.04161046 -0.00239938  0.00184681  0.00483125
   0.02619633 -0.03283904  0.0243705  -0.03910375]
 [ 0.04267612 -0.03350116 -0.0234298   0.00746056 -0.03464542  0.0317754
  -0.04463515  0.03101057  0.04890628  0.01694882]
 [-0.03820832 -0.04938891  0.03143836 -0.00529527 -0.02088292  0.01896072
   0.02210693  0.02839288  0.01945493 -0.02051385]
 [ 0.00772226 -0.04961765 -0.04692031  0.00286301 -0.04634292 -0.03382219
   0.01582136 -0.01889046  0.01990343  0.03978669]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[-0.01597375  0.01124644  0.04702612 -0.02477637 -0.02166818 -0.00692565
   0.00137762  0.03707198  0.04972422  0.04412607]
 [-0.02947437 -0.00324265 -0.04161046 -0.00239938  0.00184681  0.00483125
   0.02619633 -0.03283904  0.0243705  -0.03910375]
 [ 0.04267612 -0.03350116 -0.0234298   0.00746056

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]
# https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews